### ISSUE TITLE
Add clear contributor docs 

### ISSUE THREAD

**Issue by DarikshaAnsari** [in-toto/in-toto.io#25]
Description:

This issue is created to add a "CONTRIBUTING.md" file to the repository. The CONTRIBUTING.md file will provide guidelines and instructions for contributors on how to contribute to the project effectively. It will include information on setting up the project locally, installing dependencies, coding standards, testing procedures, and submitting pull requests.

Expected Outcome:

Once this issue is completed, contributors will have clear guidelines and instructions on how to contribute to the project. This will streamline the contribution process, encourage community involvement, and improve the overall quality of the project.

**Comment by lukpueh** [comment]
Fixed by #26
