### ISSUE TITLE
Add README.md file to in-toto.io repository

### ISSUE THREAD

**Issue by Ayush9026** [in-toto/in-toto.io#27]
## Description:
The in-toto.io repository currently lacks a README.md file, which is essential for providing an overview of the project, installation instructions, usage examples, and contribution guidelines. A comprehensive README.md file will help new contributors and users understand the purpose and functionality of the project.

**Comment by lukpueh** [comment]
You could link to the newly added CONTRIBUTING.md file

**Comment by Ayush9026** [comment]
@lukpueh Sir thank you for the suggestion! I'll link the new CONTRIBUTING.md in the README.md to guide new contributors. This will provide clear instructions and make it easier for newcomers to get involved. A good README.md should always link to the CONTRIBUTING.md to streamline the onboarding process.

**Comment by chalin** [comment]
@lukpueh - please assign this to @DarikshaAnsari.

@DarikshaAnsari - for now, submit a simple PR with a README.md following the TUF website as a (very) minimalistic example: https://github.com/theupdateframework/theupdateframework.io/blob/master/README.md
