### ISSUE TITLE
Rename `master` to `main`

### ISSUE THREAD

**Issue by chalin** [in-toto/in-toto.io#42]
This is following most other CNCF repos. For details see:

- [Renaming the default branch from master](https://github.com/github/renaming?tab=readme-ov-file#renaming-the-default-branch-from-master)
- https://inclusivenaming.org
- [Cloud Native Computing Foundation’s Inclusive Naming Initiative](https://www.cncf.io/announcements/2021/05/04/cloud-native-computing-foundations-inclusive-naming-initiative-selected-as-honorable-mention-in-the-software-category-of-fast-companys-2021-world-changing-ideas-awards/)

**Comment by chalin** [comment]
@lukpueh - I'd handle the rename, which should be seamless, but I don't have the permissions. Can you handle it, or grant me the necessary permissions?

Btw, I can confirm that I can (force) push to the `docsy` branch.

**Comment by lukpueh** [comment]
Please go ahead with the rename, if you don't mind. I updated your permissions.

**Comment by chalin** [comment]
<img width="386" alt="image" src="https://github.com/user-attachments/assets/11040f8d-0bef-41b8-9964-b68545faeba3">


```bash
  git branch -m master main
  git fetch origin
  git branch -u origin/main main
  git remote set-head origin -a
  ```

**Comment by chalin** [comment]
@DarikshaAnsari ☝️
