### ISSUE TITLE
[redirects] Don't version control files under the auto-generated `public` directory

### ISSUE THREAD

**Issue by chalin** [in-toto/in-toto.io#43]
Currently the Netlify `_redirects` file is being edited directly from the Hugo-generated `public` directory. It should not be setup in that way.

Instead move the file to `static/_redirects`.

Later we can consider switching to using Hugo aliases, and eventually an implementation of Hugo aliases via Netlify redirects as has been done elsewhere, such as https://github.com/open-telemetry/opentelemetry.io/issues/781.

Waiting for the following to be merged first:

- [x] #23
- [x] #38

**Comment by lukpueh** [comment]
@chalin, this should be unblocked now
