### ISSUE TITLE
Ensure that https://app.netlify.com/sites/in-toto/deploys is public

### ISSUE THREAD

**Issue by chalin** [in-toto/in-toto.io#47]
@JustinCappos @lukpueh - any objections to making https://app.netlify.com/sites/in-toto/deploys public? It's public for (at least) some other CNCF projects (I honestly haven't surveyed how many :)). It's useful for any contributor to be able to see the Netlify-related action statuses, including the build log of PRs they submit.

I don't know how to configure that, but I'm willing to take a look if/once I'm granted access.

**Comment by lukpueh** [comment]
No objections. Thanks for taking a stab at it!

**Comment by lukpueh** [comment]
Builds seem to be public by default. See #49. If we want to change them we  have various site protection options: https://docs.netlify.com/security/secure-access-to-sites/site-protection/
