### ISSUE TITLE
Netlify build failures

### ISSUE THREAD

**Issue by chalin** [in-toto/in-toto.io#48]
As you can see from the following screenshot taken from [this Netlify build](https://app.netlify.com/sites/in-toto/deploys/66842f0c25600ab09056a2e2): the last **production build was on November 7, 2023**. Strange.

![image](https://github.com/in-toto/in-toto.io/assets/4140793/cc9df5bf-2933-4767-98b6-ed870bbd374c)

 When I tried to manually trigger a build, it failed due to git access issues.

```text
12:47:22 PM: Failed during stage 'preparing repo': For more information, visit [https://docs.netlify.com/configure-builds/troubleshooting-tips/#build-fails-with-error-128:](https://docs.netlify.com/configure-builds/troubleshooting-tips/?_gl=1*1fav0ql*_gcl_au*MTk3Nzk0NjAuMTcxOTUyMDI4MA..#build-fails-with-error-128:) Host key verification failed.
```

I'll investigate further and report back.

**Comment by chalin** [comment]
From the Netlify docs at https://docs.netlify.com/configure-builds/troubleshooting-tips/#build-fails-with-exit-status-128:

> We only have permission to create a copy of your code when you link the repository. If you are seeing your build fail with exit status 128 in the deploy log, relinking your repo using our UI is a good first attempt to fix things (go to [Site configuration > Build & deploy > Continuous deployment > Repository](https://app.netlify.com/sites/in-toto/configuration/deploys#repository), select Manage repository, then Link to a different repository). If you do this, please check your webhook settings at your Git provider to be sure you don’t have any duplicate Netlify webhooks.

@lukpueh - as suggested above, could you unlink and relink this repo to the Netlify account via:

> <img width="970" alt="image" src="https://github.com/in-toto/in-toto.io/assets/4140793/e518319b-9b24-4c29-bde5-bff7d023d050">

**Comment by lukpueh** [comment]
Thanks for the instructions. Unlinking and relinking did the trick:

https://app.netlify.com/sites/in-toto/deploys/66851b672b41ecca15db4b09
